### ISSUE TITLE
Misleading names for internal metrics

### ISSUE THREAD

**Issue by csibbitt** [infrawatch/smart-gateway#41]
Internally generated metrics such as `sa_collectd_total_amqp_message_recv_count` and `sa_collectd_total_amqp_processed_message_count` should probably not have the `sa_collectd` prefix. If we like `sa` then maybe `sa_smartgateway` or `sa_internal`, but they aren't from collectd, so should not be labelled as such.

**Comment by leifmadsen** [comment]
@csibbitt I believe we can close this as it was addressed in sg-core?
