### ISSUE TITLE
Prometheus scrape endpoint only shows each metric once

### ISSUE THREAD

**Issue by csibbitt** [infrawatch/smart-gateway#42]
Right now, each metric process by the SG will only ever be displayed once on the Prometheus scrape page. I don't think this is the correct behavior for a prometheus scrape endpoint, in general I expect them to return the latest data they have for each metric that is still "live" [CITATION NEEDED!]

Some of the implications:
* Metrics prematurely set to stale
  * "If a target scrape or rule evaluation no longer returns a sample for a time series that was previously present, that time series will be marked as stale."  (https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness)
  * Timing skew can cause certain metrics not to appear in a given scrape
  * This leads to non-intuitive results when doing instant queries and basic graphs in the prom UI
    * Users think metrics are missing, but actually they are there, just perpetually going stale so harder to query for
* If there were two prometheus' scraping it (a common deployment for HA, which we hope to implement) each would only see half the data 
  * Actually that's just the best case. If the scrapes are back-to-back, one instance would get the vast majority of the data!
* Manual checking of the SGs metrics page, or any other interaction (like an errant health check, for example) will result in dropped metrics in the system of record

After discussing it with others, I have a feeling this functionality may have originally been intentional as part of some experiments to maximize the SG -> Prom throughput (multiple proms scraping multiple endpoints, each delivering a subset of the metrics). I think that's worth nothing for the record, because sharding the data may be a useful technique for us to continue to explore, but I think this implementation is a bit too simplistic and is getting in the way of simple use cases.

**Comment by atyronesmith** [comment]
Hmmm...  I believe that the current operation is correct.  If data did not clear out, the same value would be stored in prometheus repeatedly.  The default sample behavior  of  Prometheus apply the time stamp from the scrap not from the incoming sample.  

As for HA, there should be two SG with the data replicated by the AMQP protocol.  Otherwise, the SG is a single point of failure.

What is the problem that is being seen related to this?

**Comment by mrunge** [comment]
shouldn't the timestamp come from the data collector, i.e collectd?

Prometheus will drop duplicate metrics identified via timestamp. The issue with this approach is, that you can easily loose metrics e.g by curling the scrape end-point.

**Comment by aneeshkp** [comment]
The default timestamp was coming from Prometheus . When SG was developed , Prometheus didn’t allow to push the timestamp. Later when it was available , the  smartgateway was  updated  to use time stamp from collectd.

**Comment by csibbitt** [comment]
My apologies; this is a long one.

@atyronesmith - The main problem we're seeing that I believe is related to this, is when I've helped people set up SAF they typically report that data is not making it to Prometheus even though everything appears to be set up correctly. In each case, SAF is working fine but the data is awkward to query so users think it's broken. Typically we get a screenshot like this:

![telemetry](https://user-images.githubusercontent.com/5091372/66850064-0b6db880-ef46-11e9-8c30-6881b1f890f4.PNG)

In this screenshot you can see that Prometheus is aware of the metrics being collected (the series names appear in the legend), but isn't putting any of them on the graph.

If I switch to the table view and type `sa_collectd_cpu_total` I get the message "no data", whereas if I query `sa_collectd_cpu[15m]` I see the samples. It hasn't been proven yet, but I believe this unexpected behavior is because of this Issue, and Prometheus marking series stale when they shouldn't be due to timing of metrics delivery vs. scraping. More experiments are definitely required to be sure this would solve the problem.

Next up, HA. I agree that the preferred HA architecture for SAF uses two SGs. I was referring to the common HA architechture implemented for Prometheus itself, which is to have multiple Prom's querying the same endpoints. (See https://github.com/coreos/prometheus-operator/blob/master/Documentation/high-availability.md#prometheus) Given this mode of HA operation for Prometheus, it's clear that it expects the endpoint to deliver (~roughly) the same data to each scraper. With the current Smart Gateway implementation, instead of two Prom's with largely the same data, you'd get two entirely disjoint data sets. Whether this matters for an HA deployment of SAF or not is beside the point, it clearly shows that the current behavior is not what is generally expected of a Prometeus scrape endpoint.

Next on the theme of expected behavior, let's compare what the SG does to what other endpoints do in our system. For the QDR, Prometheus, and the Node Exporters, when I query the /metrics endpoint twice in rapid succession (<1s), they return largely the same data each time. For some endpoints the exact list of metrics can change; for example as you mount and unmount file systems, each of them gets exposed via the metrics endpoint; but while a filesystem is mounted every single scrape will return every stat for that filesystem. The Smart Gateway is the only metrics endpoint in our system (or indeed that I've ever seen) that returns a different set of metrics names every time I query it (if I query it quickly). If someone erroneously sets up a health-check to hit the SG /metrics endpoint, every time the healthcheck fires, metrics will go missing. This doesn't seem right.

Finally, we can compare it to the Prometheus Push Gateway, which I'd argue is essentially what we're building (with AMQP instead of REST). There are many issues opened against the PGW asking for a TTL for metrics. See: https://github.com/prometheus/pushgateway/issues/19 as just the first example. That issue states "Currently every node needs to be deleted explicitly or the last value will stick around forever", describing what is essentially an infinite TTL. The official treatment of this topic is on the developers mailing list: https://groups.google.com/forum/#!topic/prometheus-developers/9IyUxRvhY7w and the first message there says "But sometimes those hosts crash, and instead of having no data we see in our graphs flat lines equivalent to the metrics' values in the last push." again describing an infinite TTL. I'm not intending to have an argument about the TTL issue here, but merely want to point out that the SG essentially has a 0 TTL, which is the exact opposite of the infinite TTL in the PGW.

@aneeshkp  - Thank you for the history on the timestamps! Unfortunately, the current default appears to have timestamps disabled (there are none visible on the metrics endpoint page). I do see the `-usetimestamp` argument in the SG source code, and it appears to default on, but I guess it doesn't work? This option isn't exposed through the operator, so I can't turn it on or off for experiments in my current setup. We should take a closer look at this, but I believe it is actually irrelevant to the misbehavior I'm describing in this issue.

**Comment by atyronesmith** [comment]
What is the current prometheus scrape period?  

I see what you are saying.  If you change the scrape period to a larger value, say 1 minute do you see
issues?  Also, what is the data collection period for collectd?  The period should be <= to the prometheus scrape period.  

In the bigger picture.  Removing the implicit cache clear probably won't work as the scrape will become to large and there will be an HTTP timeout on the GET.  We had seen similar behavior while doing the preliminary testing, but keeping the collectd period <= the scrape period looked to be the solution.  

If that is no longer the case (or never was really a solution), the best solution is to break the single scrape into multiple scrapes.  Service discovery would either need to be made dynamic.  A scrape target would be an individual host / port pair.   

As far as TTL, it should be set to twice the max collectd sample period.  (assuming all the periods are the same across all the hosts).

The immediate cache clear can be removed as it is clearly affecting Prometheus.  I believe there is a TTL feature in the SG code (unless it has been removed).  Incorrect data is better than a non-functioning system.  The problem as you know is that we are synthesizing a proxy for remote data points to allow for the use of Promethues.

HA....   If you remove the explicit cache clear, then you should be able to do the standard Prometheus HA.  I still find it funny that they recommend this method of "HA".  The better method would be to multicast the data (As I thought it was already) to the two SGs.  In either case, the data between the two Prometheus are not going to be identical.  The AMQP-based method has the change of being more closely linked as the duplication is at the last router hop.  However, just duplicating the database in Ceph or with rdb is a more sane approach as you only need to run one Prometheus and you fire up another one if the first one dies (using the backup).  

Nice, thorough examination and explanation of the design's shortcomings.  Let me know now I can help.

**Comment by csibbitt** [comment]
>What is the current prometheus scrape period?

I don't know for the example I posted, but I can tell you that I see similar behavior (though less pronounced, it's sporadic) when both Prometheus and Collectd are configured for 1s intervals, which is currently the default for our installation process. Jitter in the link can cause it, basically.

Your intuition is totally correct, if we raise the prometheus scrape period this goes away, and conversely, making the collectd period longer is a sure fire way to trigger it. 

> Removing the implicit cache clear probably won't work as the scrape will become to large and there will be an HTTP timeout on the GET

Based on my current testing, this is exactly where I expect the next bottleneck, even with the current algorithm. The scrape times often creep up to nearly 1s under load, which given the current AMQP read bottleneck is no more than 15,000 metrics/scrape. Our target output is 100,000 metrics/scrape. That's a lots of HTTP data and it makes me wonder if some sort of sharding of the endpoints needs to happen sooner than we thought. I'd like to re-evaluate after I complete some other performance work on the SG code and get a closer look at this.

> As far as TTL, it should be set to twice the max collectd sample period. (assuming all the periods are the same across all the hosts).

2x the max interval is a good suggestion. Unfortunately, we were planning to lengthen the interval of some collectd plugins in order to reduce total metrics load (some plugins, like uptime, do not benefit from a 1s interval), so this would need to be set either per-series (yikes) or at least long enough to accommodate the longest metric interval in your cloud. That's probably not horrible.

**Comment by atyronesmith** [comment]
A large set of the metrics can be moved to a much longer sample period.  Have been thinking about "sharding".   My initial reaction was the obvious sharding by host.  However, you still have the issue of different metrics having different update periods.  If I remember correctly, the collectd format carries the sample period with the metric in the metric bundle.  A crazy idea would be to shard by sample period.  For example, the SG puts all 1 minute data from all hosts into one map, 30 seconds in another, ... 1 second in the 1 second map.  Each map would be exposed as a different endpoint and Prometheus would be setup with multiple targets.  Prometheus allows different poll periods per target so each target would be set with the proper poll period.  

This arrangement would allow several targets and allow Prometheus to use multiple goroutines and more importantly multiple threads to be used.  Prometheus / Go do a good job of scheduling so it should spread the load.  For example, one vcpu might only service the 1s target and another vcpu might service 1m, 30s, etc...

**Comment by atyronesmith** [comment]
Yes.  You are correct.  Sharding only works well when there is an even distribution. A hierarchal sharding approach is probably needed.  Bin first by period and then by a well know hash.  (i.e. hash on metric name for 1s metrics)....  always setup N endpoints for 1s.  Names always map to the same endpoint.

**Comment by leifmadsen** [comment]
This was addressed in the SG re-write via https://github.com/infrawatch/sg-core. The change won't be added here, but rather ceilometer metrics support will be added to sg-core. Closing this as _won't fix_.
