### ISSUE TITLE
[refactor candidate] amqp10 func start()

### ISSUE THREAD

**Issue by leifmadsen** [infrawatch/smart-gateway#59]
Looking at the SG golang report card, the gocyclo feedback identifies a function that seems like it could be broken down a bit into more consumable chunks for easier understanding.

https://goreportcard.com/report/github.com/redhat-service-assurance/smart-gateway#gocyclo

> Gocyclo calculates cyclomatic complexities of functions in Go source code. The cyclomatic complexity of a function is calculated according to the following rules: 1 is the base complexity of a function +1 for each 'if', 'for', 'case', '&&' or '||' Go Report Card warns on functions with cyclomatic complexity > 15.
> 
>         smart-gateway/internal/pkg/amqp10/receiver.go
>         Line 197: warning: cyclomatic complexity 16 of function (*AMQPServer).start() is high (> 15) (gocyclo)

https://github.com/redhat-service-assurance/smart-gateway/blob/master/internal/pkg/amqp10/receiver.go#L196-L268

Basically it looks like this function is too complex and could be broken into smaller consumable components.

**Comment by paramite** [comment]
It indeed is ... for example "s.method(s)" is unnecessary complex construct IMO. IIUC the "method" parameter of the struct is basically pointer to the method "connect"  ... for what reason this was initially used I have no idea, but IMO calling "c.connect()" seems much more readable to me.

**Comment by csibbitt** [comment]
I was also scratching my head about the abstraction of `s.method()` when I came across it. For sure there is some further abstraction possible in here.

**Comment by leifmadsen** [comment]
Closing as part of grooming. RFEs will not be resolved in the legacy Smart Gateway.
