### ISSUE TITLE
Ceilometer events stored in wrong index

### ISSUE THREAD

**Issue by pleimer** [infrawatch/smart-gateway#77]
For https://github.com/infrawatch/smart-gateway/pull/71

Ceilometer events are being stored in `collectd_generic` ElasticSearch index instead of `ceilometer_generic`:

```
{
  "collectd_generic" : {
    "aliases" : { },
    "mappings" : {
      "properties" : {
        "context" : {
          "type" : "object"
        },
        "request" : {
          "properties" : {
            "oslo" : {
              "properties" : {
                "message" : {
                  "type" : "text",
                  "fields" : {
                    "keyword" : {
                      "type" : "keyword",
                      "ignore_above" : 256
                    }
                  }
                },
                "version" : {
                  "type" : "text",
                  "fields" : {
                    "keyword" : {
                      "type" : "keyword",
                      "ignore_above" : 256
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "settings" : {
      "index" : {
        "creation_date" : "1582923311483",
        "number_of_shards" : "1",
        "number_of_replicas" : "1",
        "uuid" : "DvsMFgwYT7C0T1_9ZuC9OQ",
        "version" : {
          "created" : "7050199"
        },
        "provided_name" : "collectd_generic"
      }
    }
  }
}
```

**Comment by leifmadsen** [comment]
@pleimer I think I figured out why we're seeing this wrong. The Smart Gateway Operator wasn't update to account for a new struct type. See https://github.com/infrawatch/smart-gateway/blob/master/internal/pkg/saconfig/config.go#L43-L47

Looks like we're supposed to migrate away from `AMQPEventURL` and move to `AMQP1Connection` which has two sub-parameters: `URL` and `DataSource`.

The value of `DataSource` needs to be set to `universal`, `collectd`, or `ceilometer`.

**Comment by leifmadsen** [comment]
Opened https://github.com/infrawatch/smart-gateway-operator/issues/42

**Comment by leifmadsen** [comment]
Closing this issue as it's more of a configuration problem than a bug.
