### ISSUE TITLE
Smart Gateway can't start if using new AMQP1Connections method

### ISSUE THREAD

**Issue by leifmadsen** [infrawatch/smart-gateway#79]
Issue is here: https://github.com/infrawatch/smart-gateway/blob/master/internal/pkg/metrics/metrics.go#L140-L144

**Comment by leifmadsen** [comment]
Frankly I think I just want to remove all the flags entirely, and just have a configuration file. The Smart Gateway is pretty much never used outside of OpenShift, and we don't really pass flags directly to the code.

I would suggest only leaving the `-config` flag.

**Comment by leifmadsen** [comment]
Also realized we need the `-servicetype` but I'd actually prefer to just remove that as well and add a new configuration option in the file for `json:ServiceType`.

**Comment by leifmadsen** [comment]
@csibbitt @pleimer @paramite what do you think?

**Comment by pleimer** [comment]
That makes sense to me. The config location flag says `"Path to configuration file(optional).if provided ignores all command line options"`, yet a check for the AMQP1MetricUrl is hard coded in after reading the file (I guess that's what this bug is about). Anyway, I like the idea of solely using a config file, granted it should have a default location if not specified by `-c`. Especially since the number of start up items has expanded

**Comment by leifmadsen** [comment]
Yea I just feel like having all these flags and the extra checks makes the code more verbose than it would otherwise need to be, and provides just more locations that we need to track commands. As it stands right now, we have the following tree:

* Service Telemetry Operator writing a CR (with variables passed to it)
* Smart Gateway Operator with a CRD holding config options
* Smart Gateway Operator with templates holding CR parameters
* Smart Gateway command line flags
* Smart Gateway configuration file passed to internal struct

Just a lot of areas to coordinate, and this doesn't even include documentation, molecule testing, smoketest setup, quickstart setup, etc.

**Comment by leifmadsen** [comment]
Ugh this is actually still required because `AMQP1Connections` is not actually implemented for `metrics.go` yet, which means I'll need to leave this part of the code here.

**Comment by leifmadsen** [comment]
OK merge the flag removal changes. No issue here on the metrics.go side of things since the code isn't implemented yet.
