### ISSUE TITLE
Parsing sensubility result gets SG down

### ISSUE THREAD

**Issue by paramite** [infrawatch/smart-gateway#91]
Currently SG fails when parsing collectd event:
{"labels":{"check":"elastic-check","client":"lenovo-p720-rdo-13.tpb.lab.eng.brq.redhat.com","severity":"FAILURE"},"annotations":{"command":"podman ps | grep elastic || exit 2","duration":0.042233102,"executed":1601895830,"issued":1601895830,"output":"time=\"2020-10-05T13:03:50+02:00\" level=error msg=\"cannot mkdir /run/user/0/libpod: mkdir /run/user/0/libpod: permission denied\"\n","status":2,"ves":"{\"commonEventHeader\":{\"domain\":\"heartbeat\",\"eventType\":\"checkResult\",\"eventId\":\"lenovo-p720-rdo-13.tpb.lab.eng.brq.redhat.com-elastic-check\",\"priority\":\"High\",\"reportingEntityId\":\"b37ab430-6fee-4f5a-9a99-2576e1bf79cb\",\"reportingEntityName\":\"lenovo-p720-rdo-13.tpb.lab.eng.brq.redhat.com\",\"sourceId\":\"b37ab430-6fee-4f5a-9a99-2576e1bf79cb\",\"sourceName\":\"lenovo-p720-rdo-13.tpb.lab.eng.brq.redhat.com-collectd-sensubility\",\"startingEpochMicrosec\":1601895830,\"lastEpochMicrosec\":1601895830},\"heartbeatFields\":{\"additionalFields\":{\"check\":\"elastic-check\",\"command\":\"podman ps | grep elastic || exit 2\",\"duration\":\"0.042233\",\"executed\":\"1601895830\",\"issued\":\"1601895830\",\"output\":\"time=\\\"2020-10-05T13:03:50+02:00\\\" level=error msg=\\\"cannot mkdir /run/user/0/libpod: mkdir /run/user/0/libpod: permission denied\\\"\\n\",\"status\":\"2\"}}}"},"startsAt":"2020-10-05T13:03:50+02:00"}

With:
2020/10/05 13:03:50 collectd.go:86: invalid character '2' after object key:value pair

**Comment by leifmadsen** [comment]
Closed due to merge of #92
